name: Build

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  linux-build:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Update dependencies
        run: sudo apt-get update
      - name: Install dependencies
        run: sudo apt-get install nodejs chromium-browser
      - name: Set up cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build
        run: ./gradlew build -Dsplit_targets
      - name: Android instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 21
          arch: x86
          disable-animations: true
          script: ./gradlew :extensions-compose-jetpack:connectedDebugAndroidTest --stacktrace
